<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tpl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{%?</string>
	<key>foldingStopMarker</key>
	<string>%?\}</string>
	<key>name</key>
	<string>Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.template</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%?\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.template</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.template</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lang</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.template</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*(%?\})</string>
					<key>name</key>
					<string>comment.block.template</string>
					<key>patterns</key>
					<array/>
				</dict>
			</array>
		</dict>
		<key>lang</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(eq|ne|gte|gt|lte|lt|not|is|to|in)\b</string>
					<key>name</key>
					<string>keyword.operator.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE|true|false|array|empty|defined)\b</string>
					<key>name</key>
					<string>constant.language.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else|elseif|elif|foreach|for|break|display)\b</string>
					<key>name</key>
					<string>keyword.control.template</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([a-zA-Z]+)=</string>
					<key>name</key>
					<string>meta.attribute.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b()\b</string>
					<key>name</key>
					<string>support.function.built-in.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|(leftpad_.\d+|count|len)</string>
					<key>name</key>
					<string>support.function.variable-modifier.template</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.template</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.template</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.template</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.template</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.template</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.template</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.template</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.template</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\$)Smarty\.</string>
					<key>name</key>
					<string>variable.other.global.template</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.other.template</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.other.template</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.template</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.object.template</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.template</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.template</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)(\().*?(\))</string>
					<key>name</key>
					<string>variable.other.template</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.template</string>
	<key>uuid</key>
	<string>6da52972-8eac-45fb-bd80-b48a203f8af0</string>
</dict>
</plist>
